#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

wclean geometricVoF
wclean laserHeatSource
wclean electronBeamHeatSource
wclean transportModels/incompressible
wclean turbulenceModel

#------------------------------------------------------------------------------
